### ISSUE TITLE
console error when scroll

### ISSUE THREAD

**Issue by luxuze** [echoulen/react-pull-to-refresh#14]
Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
PullToRefresh.onTouchMove @ PullToRefresh.js:144

**Comment by dennis-gonzales** [comment]
I have this issue too, has this been resolved?

**Comment by dennis-gonzales** [comment]
> I have this issue too, has this been resolved?

Fixed it

PullTtoRefresh.js

`e.preventDefault();`
Replace this code with

`if(e.cancelable) {
    e.preventDefault();
}`
