### ISSUE TITLE
The containers have set height: 'auto' with no way to override

### ISSUE THREAD

**Issue by sgurjeet** [echoulen/react-pull-to-refresh#15]
The two containers that are rendered in default state have their height property set to 'auto' which causes issues in display on children components.
IMO, there should be a way to override that property as well. Like, in my case I need it as '100%'.

**Comment by kalarsen** [comment]
This is driving me nuts. Anyone have a workaround? I'd like the control to have 100% height.

**Comment by jbeuckm** [comment]
This might help you: https://github.com/echoulen/react-pull-to-refresh/pull/16/files

**Comment by adisatriak** [comment]
this issue happens to me as well :(

**Comment by awreese** [comment]
Yes, definitely need this functionality. Can we get https://github.com/echoulen/react-pull-to-refresh/pull/16/files merged?

**Comment by echoulen** [comment]
https://github.com/echoulen/react-pull-to-refresh/releases/tag/v1.2.3
