### ISSUE TITLE
Support React Lower version ?

### ISSUE THREAD

**Issue by DaveNguyenHuy** [echoulen/react-pull-to-refresh#2]
I tried a demo, Its works, but It didnt call onRefresh function when I add this module to my project used react 15.6.2. I wonder because of the version of React, Does this module support React and ReactDOM 15.6.2 :(

**Comment by echoulen** [comment]
onRefresh should be a promise function.
May you try this
```
const asyncFunc = () => new Promise((resolve) => {
    console.log("run asyncFunc")
    resolve();
});
```

and

`onRefresh={asyncFunc}`
