### ISSUE TITLE
Hardcoded backgroundColor should not be obligatory or at least be customizable

### ISSUE THREAD

**Issue by TheTostu** [echoulen/react-pull-to-refresh#4]
https://github.com/echoulen/react-pull-to-refresh/blob/90eee3f55f00fcad14b4882c54592bf5fd01df11/src/components/PullToRefresh.tsx#L187

This div's background color is unnecessary hardcoded and affects inner divs. There is no need to demand white background of the divs in the menu. It should not be there.

**Comment by echoulen** [comment]
done by #6
